Artifacts, UI & Control
KoolieAid/CookingYnah pull request #21
Opened 2023-07-02 10:55 UTC by AlexanderGregorSanchez

Artifacts: (placeholders at the moment)
-Fire Meatball
-Ground Wave(from eric to be added)
-Spectral Sword

2023-07-15 16:12 UTC, LauSnchzz commented on Assets/FaceToCameraHorizon.cs
maybe place na lng sa folder toh

2023-07-15 17:34 UTC, LauSnchzz commented on Assets/Scripts/Managers & Handlers/ArtifactUIHandler.cs
change some commented lines if they are not being used or are TODO so we can distinguish it in the future

2023-07-15 17:35 UTC, LauSnchzz commented on Assets/Scripts/Player Folder/Player.cs
if commented line will not be used in the future, remove

2023-07-15 17:47 UTC, LauSnchzz commented on Assets/Scripts/Abilities/Jab.cs
maybe change this script's folder so that it wont be confusing since this is the basic attack and not a special ability

2023-07-15 18:04 UTC, LauSnchzz requested changes
Check the comments and resolve na lng on ur own pero so far so good na man we just need to glue everything together!

2023-07-15 18:04 UTC, LauSnchzz commented on Assets/Scripts/Abilities/Meteor.cs
would this still be implemented? is this supposed to be a ability? if its not being used maybe add a comment at line 5 like //NOT BEING USED or POSSIBLE FEAUTRE [NOT IMPLEMENTED]

2023-07-17 05:20 UTC, AlexanderGregorSanchez commented on Assets/Scripts/Abilities/Meteor.cs
just forgot to add it to the meteor prefab. oops

2023-07-17 08:06 UTC, LauSnchzz approved these changes
nicee niceee

2023-07-17 08:06 UTC, merged